definitions:
  base.Response:
    properties:
      data:
        type: object
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /manager/{some_id}:
    get:
      consumes:
      - application/json
      description: get record by ID
      parameters:
      - description: managerId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
  /manager/create/:
    post:
      consumes:
      - application/json
      description: 创建管理用户
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 用户类型
        in: query
        name: tp
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 创建管理用户
      tags:
      - 管理用户
  /manager/list/:
    get:
      consumes:
      - application/json
      description: 获取所有管理用户
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 条数
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 页数
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 获取所有管理用户
      tags:
      - 管理用户
swagger: "2.0"
