definitions:
  base.ListResponse:
    properties:
      data:
        description: 数据
        type: object
      page:
        description: 页数
        type: integer
      pageSize:
        description: 每页条数
        type: integer
      total:
        description: 总条数
        type: integer
    type: object
  base.Response:
    properties:
      data:
        description: 数据
        type: object
    type: object
  controller.CaptchaResponse:
    properties:
      captchaId:
        description: 验证码Id
        type: string
      imageUrl:
        description: 验证码图片url
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /base/captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CaptchaResponse'
      summary: 获取验证码
      tags:
      - 验证码
  /base/captcha/image:
    get:
      consumes:
      - application/json
      description: 获取验证码图片
      produces:
      - application/json
      responses:
        "200":
          description: 图片地址
          schema:
            type: string
      summary: 获取验证码图片
      tags:
      - 验证码
  /base/captcha/verify:
    post:
      consumes:
      - application/json
      description: 校验验证码
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 校验验证码
      tags:
      - 验证码
  /base/version:
    get:
      consumes:
      - application/json
      description: 获取版本
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取版本
      tags:
      - 获取版本
  /web/manager/{id}:
    get:
      consumes:
      - application/json
      description: 获取管理员信息
      parameters:
      - description: 管理员id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 获取管理员信息
      tags:
      - 管理用户
  /web/manager/{id}/del:
    post:
      consumes:
      - application/json
      description: 删除管理员
      parameters:
      - description: 管理员id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 删除管理员
      tags:
      - 管理用户
  /web/manager/{id}/edit:
    post:
      consumes:
      - application/json
      description: 刷新令牌
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: token:XXXXXXXX
          schema:
            type: string
      summary: 刷新令牌
      tags:
      - 管理用户
  /web/manager/create/:
    post:
      consumes:
      - application/json
      description: 采集数据
      parameters:
      - description: openId
        in: query
        name: open_id
        required: true
        type: string
      - description: 来源类型 0未知 1微信小程序 2安卓 3IOS 4WEB 5其他
        in: query
        name: source_tp
        required: true
        type: string
      - description: 项目token
        in: query
        name: token
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 采集数据
      tags:
      - 埋点
  /web/manager/list/:
    get:
      consumes:
      - application/json
      description: 获取所有管理用户
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 条数
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 页数
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.ListResponse'
      summary: 获取所有管理用户
      tags:
      - 管理用户
  /web/project/{id}:
    get:
      consumes:
      - application/json
      description: 获取项目信息
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 获取项目信息
      tags:
      - 管理项目
  /web/project/{id}/del:
    post:
      consumes:
      - application/json
      description: 删除项目
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 删除项目
      tags:
      - 管理项目
  /web/project/{id}/edit:
    post:
      consumes:
      - application/json
      description: 编辑项目信息
      parameters:
      - description: 项目名称
        in: query
        name: name
        required: true
        type: string
      - description: 资源
        in: query
        name: resource_path
        required: true
        type: string
      - description: 项目api
        in: query
        name: rest_api
        required: true
        type: string
      - description: 端口号
        in: query
        name: port
        required: true
        type: integer
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 编辑项目信息
      tags:
      - 管理项目
  /web/project/{id}/refreshToken:
    post:
      consumes:
      - application/json
      description: 刷新项目token
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 刷新项目token
      tags:
      - 管理项目
  /web/project/create/:
    post:
      consumes:
      - application/json
      description: 项目创建
      parameters:
      - description: 项目名称
        in: query
        name: name
        required: true
        type: string
      - description: 资源
        in: query
        name: resource_path
        required: true
        type: string
      - description: 项目api
        in: query
        name: rest_api
        required: true
        type: string
      - description: 端口号
        in: query
        name: port
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 项目创建
      tags:
      - 管理项目
  /web/project/list/:
    get:
      consumes:
      - application/json
      description: 获取所有项目
      parameters:
      - description: 项目名
        in: query
        name: name
        required: true
        type: string
      - description: 条数
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 页数
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.ListResponse'
      summary: 获取所有项目
      tags:
      - 管理项目
swagger: "2.0"
